import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/Footer";
import { Toaster } from "react-hot-toast";
import { Providers } from "../redux/providers";
import NavigationBar from "@/components/shared/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <Providers>
          <div className="lg:px-20 ">
            <NavigationBar />
            <Toaster position="top-center" />
            <div className="min-h-screen px-7 lg:px-7">{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
